--- #YAML:1.0
name:               Catalyst-Action-RenderView-ErrorHandler-Action-Email
version:            0.02
abstract:           Catalyst ErrorHandler Action for Email
author:
    - Stefan Profanter <profanter@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Catalyst::Action::RenderView::ErrorHandler::Action:  0
    Moose:                0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
